require('dotenv').config();
const express = require('express');
const path = require('path');
const { getAllTodos, createTodo, updateTodo, deleteTodo, getTodoById } = require('./storage');

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// GET /api/todos - Get all todos
app.get('/api/todos', async (req, res) => {
  try {
    const todos = await getAllTodos();
    res.json({ success: true, todos });
  } catch (error) {
    res.status(500).json({ success: false, error: 'Failed to load todos' });
  }
});

// POST /api/todos - Create new todo
app.post('/api/todos', async (req, res) => {
  try {
    const { text } = req.body;

    // Validate
    if (!text || text.trim() === '') {
      return res.status(400).json({ success: false, error: 'Text is required' });
    }

    // Create todo in database (ID auto-generated by database)
    const newTodo = await createTodo(text.trim());

    res.status(201).json({ success: true, todo: newTodo });
  } catch (error) {
    res.status(500).json({ success: false, error: 'Failed to create todo' });
  }
});

// PUT /api/todos/:id - Update todo
app.put('/api/todos/:id', async (req, res) => {
  try {
    const id = parseInt(req.params.id);
    const { text, completed } = req.body;

    // Build updates object
    const updates = {};
    if (text !== undefined) {
      updates.text = text.trim();
    }
    if (completed !== undefined) {
      updates.completed = completed;
    }

    // Update in database
    const updatedTodo = await updateTodo(id, updates);

    if (!updatedTodo) {
      return res.status(404).json({ success: false, error: 'Todo not found' });
    }

    res.json({ success: true, todo: updatedTodo });
  } catch (error) {
    res.status(500).json({ success: false, error: 'Failed to update todo' });
  }
});

// DELETE /api/todos/:id - Delete todo
app.delete('/api/todos/:id', async (req, res) => {
  try {
    const id = parseInt(req.params.id);

    // Delete from database
    await deleteTodo(id);

    res.json({ success: true });
  } catch (error) {
    res.status(500).json({ success: false, error: 'Failed to delete todo' });
  }
});

// Start server
app.listen(PORT, () => {
  console.log(`Todo app running at http://localhost:${PORT}`);
  console.log('Press Ctrl+C to stop');
});
